import React from 'react';
import {
  FileText, Download, Printer, ShieldAlert, CheckCircle2,
  AlertTriangle, Pill, Activity, HeartPulse, User, Calendar,
  Globe
} from 'lucide-react';
import { ClinicalHistorySummary, PatientProfile } from '../../types';
import { FHIRService } from '../../services/fhirService';
import { useNotification } from '../../context/NotificationContext';

interface ClinicalSummaryViewProps {
  summary: ClinicalHistorySummary;
  patient: PatientProfile;
}

export const ClinicalSummaryView: React.FC<ClinicalSummaryViewProps> = ({
  summary,
  patient
}) => {
  const { showToast } = useNotification();

  const handleExportFHIR = () => {
    const fhirBundle = FHIRService.generateFHIRBundle(patient, summary);
    FHIRService.downloadJSON(fhirBundle, `FHIR_R4_ClinicalBundle_${patient.patientId}_${summary.sessionId}.json`);
    showToast('FHIR Bundle Exported', 'Downloaded ABDM & HL7 FHIR R4 compliant clinical bundle JSON.', 'VERIFICATION');
  };

  const handlePrint = () => {
    window.print();
  };

  const isMsgUrdu = summary.originalLanguage === 'ur' || (summary.originalPatientStatement && /[\u0600-\u06FF]/.test(summary.originalPatientStatement));

  return (
    <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-xl bg-teal-50 text-teal-600 border border-teal-200">
              <FileText className="w-5 h-5" />
            </span>
            <h3 className="font-extrabold text-slate-900 text-lg sm:text-xl">Pre-Arrival Clinical History Report</h3>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Generated by MediBridge AI Intake Engine • Hospital Pre-Registration
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleExportFHIR}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200 rounded-xl text-xs font-bold transition shadow-sm"
          >
            <Download className="w-3.5 h-3.5 text-teal-600" />
            <span>Export FHIR R4 JSON</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-teal-600 hover:bg-teal-700 text-white rounded-xl text-xs font-bold transition shadow-sm"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Mandatory Physician Verification Disclaimer */}
      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 flex items-start gap-3 text-amber-900">
        <ShieldAlert className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
        <div className="text-xs space-y-1">
          <p className="font-bold uppercase tracking-wider text-amber-800">
            {summary.disclaimer}
          </p>
          <p className="text-amber-900/80 leading-relaxed">
            This structured record is compiled from patient-reported symptoms and digitized medical records prior to hospital arrival. It is designed to assist clinical triage and intake efficiency. Treatment decisions must be made after in-person physician verification.
          </p>
        </div>
      </div>

      {/* Patient Bio & Identification Header */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
        <div>
          <span className="text-slate-500 font-semibold block">Patient Name &amp; ID:</span>
          <p className="font-extrabold text-slate-900 mt-0.5">{patient.patientId}</p>
        </div>
        <div>
          <span className="text-slate-500 font-semibold block">ABHA ID / Address:</span>
          <p className="font-bold text-teal-700 font-mono mt-0.5">{patient.abhaId || 'Pending ABHA'}</p>
        </div>
        <div>
          <span className="text-slate-500 font-semibold block">Demographics:</span>
          <p className="font-bold text-slate-800 mt-0.5">{patient.age} Yrs • {patient.gender} • {patient.bloodGroup}</p>
        </div>
        <div>
          <span className="text-slate-500 font-semibold block">Intake Timestamp:</span>
          <p className="font-bold text-slate-800 mt-0.5">{new Date(summary.generatedAt).toLocaleString()}</p>
        </div>
      </div>

      {/* Clinical Sections */}
      <div className="space-y-5 text-xs sm:text-sm">
        {/* Original Patient Statement & Language */}
        {summary.originalPatientStatement && (
          <div className="bg-teal-50/70 p-4 rounded-2xl border border-teal-200 space-y-1">
            <div className="flex items-center justify-between">
              <h4 className="font-bold text-teal-800 text-xs uppercase tracking-wider flex items-center gap-1.5">
                <Globe className="w-3.5 h-3.5 text-teal-600" />
                <span>Original Patient Statement</span>
              </h4>
              <span className="text-[10px] font-mono text-teal-800 bg-white px-2 py-0.5 rounded border border-teal-200 font-bold">
                Language: {(summary.originalLanguage || 'en').toUpperCase()}
              </span>
            </div>
            <p
              dir={isMsgUrdu ? 'rtl' : 'ltr'}
              className={`text-slate-900 italic text-xs sm:text-sm font-medium ${isMsgUrdu ? 'text-right font-urdu' : 'text-left'}`}
            >
              "{summary.originalPatientStatement}"
            </p>
          </div>
        )}

        {/* Chief Complaints */}
        <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200">
          <h4 className="font-bold text-teal-700 text-xs uppercase tracking-wider mb-1">
            1. Chief Complaint(s) (Standardized)
          </h4>
          <p className="text-slate-900 font-medium leading-relaxed">{summary.chiefComplaints}</p>
        </div>

        {/* History of Present Illness */}
        <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200">
          <h4 className="font-bold text-teal-700 text-xs uppercase tracking-wider mb-1">
            2. History of Present Illness (HPI)
          </h4>
          <p className="text-slate-700 leading-relaxed whitespace-pre-line">{summary.historyOfPresentIllness}</p>
        </div>

        {/* Safety Warnings & Allergies Banner */}
        {summary.safetyWarnings.length > 0 && (
          <div className="bg-red-50 border border-red-200 p-4 rounded-2xl space-y-2">
            <h4 className="font-bold text-red-700 text-xs uppercase tracking-wider flex items-center gap-1.5">
              <AlertTriangle className="w-4 h-4 text-red-600" />
              <span>3. Clinical Safety Flags &amp; Allergy Alerts</span>
            </h4>
            <div className="space-y-1">
              {summary.safetyWarnings.map((warn, i) => (
                <p key={i} className="text-xs text-red-800 leading-relaxed font-semibold">
                  • {warn}
                </p>
              ))}
            </div>
          </div>
        )}

        {/* Two-Column Grid for Meds and Conditions */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Active Medications */}
          <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200">
            <h4 className="font-bold text-teal-700 text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Pill className="w-4 h-4 text-teal-600" />
              <span>Active Medications ({summary.currentMedications.length})</span>
            </h4>
            {summary.currentMedications.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No current medications reported.</p>
            ) : (
              <div className="space-y-2">
                {summary.currentMedications.map((med, i) => (
                  <div key={i} className="p-2.5 bg-white rounded-xl border border-slate-200 text-xs flex items-center justify-between shadow-sm">
                    <div>
                      <span className="font-bold text-slate-800">{med.name}</span>
                      <span className="text-slate-500 text-[11px] block">{med.dosage} • {med.frequency}</span>
                    </div>
                    {med.indication && (
                      <span className="text-[10px] text-teal-700 bg-teal-50 px-2 py-0.5 rounded border border-teal-200 font-medium">
                        {med.indication}
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Past Medical History */}
          <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200">
            <h4 className="font-bold text-teal-700 text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Activity className="w-4 h-4 text-teal-600" />
              <span>Past Medical History ({summary.pastMedicalHistory.length})</span>
            </h4>
            {summary.pastMedicalHistory.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No chronic medical history recorded.</p>
            ) : (
              <div className="space-y-2">
                {summary.pastMedicalHistory.map((cond, i) => (
                  <div key={i} className="p-2.5 bg-white rounded-xl border border-slate-200 text-xs flex items-center justify-between shadow-sm">
                    <div>
                      <span className="font-bold text-slate-800">{cond.condition}</span>
                      <span className="text-slate-500 text-[11px] block">Diagnosed: {cond.diagnosedYear}</span>
                    </div>
                    <span className="text-[10px] text-slate-600 bg-slate-100 px-2 py-0.5 rounded font-mono">
                      {cond.status}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Known Allergies */}
        <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200">
          <h4 className="font-bold text-teal-700 text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
            <ShieldAlert className="w-4 h-4 text-teal-600" />
            <span>Documented Allergies ({summary.allergies.length})</span>
          </h4>
          {summary.allergies.length === 0 ? (
            <p className="text-xs text-slate-400 italic">No known drug or food allergies.</p>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {summary.allergies.map((all, i) => (
                <div key={i} className="p-2.5 bg-white rounded-xl border border-slate-200 text-xs flex items-center justify-between shadow-sm">
                  <div>
                    <span className="font-bold text-slate-800">{all.allergen}</span>
                    <span className="text-slate-500 text-[11px] block">{all.reaction}</span>
                  </div>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase ${
                    all.severity === 'SEVERE_ANAPHYLACTIC' ? 'bg-red-50 text-red-700 border border-red-200' : 'bg-amber-50 text-amber-800 border border-amber-200'
                  }`}>
                    {all.severity}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
