import React, { createContext, useContext, useState, useEffect } from 'react';
import { LanguageCode } from '../types';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const STORAGE_KEY = 'medibridge_preferred_language';

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: 'MediBridge AI',
    app_tagline: 'Home-to-Hospital AI Clinical Intake Platform',
    start_intake: 'Start AI Clinical Intake',
    intake_subtitle: 'Answer a few adaptive questions from home before arriving at the hospital.',
    upload_records: 'Upload Medical Documents',
    medical_timeline: 'Medical History Timeline',
    doctor_dashboard: 'Doctor Pre-Arrival Queue',
    triage_command: 'Hospital Emergency Triage',
    admin_portal: 'System Admin & Analytics',
    emergency_callout: '🚨 CRITICAL RED FLAG DETECTED',
    requires_verification: 'AI-Generated — Requires Physician Verification. Not a final diagnosis.',
    patient_id: 'Patient ID',
    abha_id: 'ABHA ID',
    triage_priority: 'Triage Priority',
    emergency_dispatch: 'Emergency Ambulance Coordination',
    consent_title: 'Patient Consent & Privacy Controls',
    verify_record: 'Physician Review & Verification',
    approve: 'Verify & Approve Record',
    edit_summary: 'Edit Clinical Summary',
    reject_summary: 'Reject / Retake Intake',
    select_hospital: 'Select Hospital & Department',
    voice_input_start: 'Speak Symptoms',
    voice_input_stop: 'Listening... Click to Finish',
    play_speech: 'Listen to AI Audio',
    talk_to_ai: 'TALK TO AI',
    talk_to_ai_sub: 'Voice or text clinical intake from home',
    upload_report: 'UPLOAD REPORT',
    upload_report_sub: 'Scan prescriptions & blood tests via OCR',
    clinical_report: 'CLINICAL REPORT',
    clinical_report_sub: 'Doctor-ready summary & safety warnings',
    health_history: 'MY HEALTH HISTORY',
    health_history_sub: 'Chronological timeline of past records',
    trusted_hospitals: 'TRUSTED HOSPITALS',
    trusted_hospitals_sub: 'Manage data sharing & hospital permissions',
    my_appointments: 'MY APPOINTMENTS',
    my_appointments_sub: 'Book OPD consultations & view tokens',
    emergency_active: 'EMERGENCY INTAKE ACTIVE',
    emergency_active_sub: 'High-risk symptoms detected — Live hospital dispatch active',
    ambulance_en_route: 'Ambulance En Route',
    eta_minutes: 'min ETA',
    call_paramedic: 'Call Paramedic',
    live_telemetry: 'Live Paramedic Telemetry & GPS',
    paramedic_unit: 'Paramedic Unit Assigned',
    view_live_map: 'View Live Ambulance Tracking',
    original_statement: 'Original Patient Statement',
    detected_concern: 'Detected Emergency Concern',
    siren_active: 'Emergency Red Siren Active',
    mute_siren: 'Mute Siren',
    unmute_siren: 'Unmute Siren',
    dispatch_status_dispatched: 'Ambulance Dispatched',
    dispatch_status_acknowledged: 'Hospital Acknowledged',
    dispatch_status_en_route: 'Ambulance En Route',
    dispatch_status_arrived: 'Arrived at Hospital',
    dispatch_status_resolved: 'Emergency Resolved',
    speech_unsupported: 'Voice input is not supported in this browser. Please use text input.',
    speech_error: 'Speech recognition error. Please try typing your symptoms.',
    chat_placeholder: 'Describe symptoms (e.g. severe chest pain, 3-day fever)...',
    send_btn: 'Send',
    start_here: 'Start Here',
    ocr_badge: 'OCR',
    report_badge: 'Report',
    history_badge: 'History',
    sharing_badge: 'Sharing',
    booking_badge: 'Booking'
  },
  hi: {
    app_title: 'मेडिब्रिज एआई (MediBridge AI)',
    app_tagline: 'घर से अस्पताल क्लिनिकल इंटेक एवं आपातकालीन ट्राइएज प्लेटफॉर्म',
    start_intake: 'एआई क्लिनिकल इंटेक शुरू करें',
    intake_subtitle: 'अस्पताल पहुँचने से पहले घर बैठे कुछ सरल सवालों के जवाब दें।',
    upload_records: 'दस्तावेज़ एवं रिपोर्ट अपलोड करें',
    medical_timeline: 'मेडिकल हिस्ट्री टाइमलाइन',
    doctor_dashboard: 'डॉक्टर प्री-अराइवल कतार',
    triage_command: 'अस्पताल आपातकालीन ट्राइएज कमांड',
    admin_portal: 'सिस्टम एडमिन एवं एनालिटिक्स',
    emergency_callout: '🚨 आपातकालीन संकेत (रेड फ्लैग) दर्ज',
    requires_verification: 'एआई-जनित सारांश — डॉक्टर द्वारा सत्यापन अनिवार्य। यह अंतिम निदान नहीं है।',
    patient_id: 'रोगी आईडी (Patient ID)',
    abha_id: 'आभा आईडी (ABHA ID)',
    triage_priority: 'ट्राइएज प्राथमिकता',
    emergency_dispatch: 'आपातकालीन एम्बुलेंस समन्वय',
    consent_title: 'रोगी सहमति एवं गोपनीयता नियंत्रण',
    verify_record: 'चिकित्सक समीक्षा एवं सत्यापन',
    approve: 'सत्यापित एवं स्वीकृत करें',
    edit_summary: 'क्लिनिकल सारांश संपादित करें',
    reject_summary: 'अस्वीकार करें',
    select_hospital: 'अस्पताल एवं विभाग चुनें',
    voice_input_start: 'बोलकर बताएं',
    voice_input_stop: 'सुन रहा है... समाप्त करने के लिए क्लिक करें',
    play_speech: 'एआई आवाज सुनें',
    talk_to_ai: 'एआई से बात करें',
    talk_to_ai_sub: 'घर से बोलकर या लिखकर लक्षण बताएं',
    upload_report: 'रिपोर्ट अपलोड करें',
    upload_report_sub: 'पर्चे व लैब रिपोर्ट ओसीआर से स्कैन करें',
    clinical_report: 'क्लिनिकल रिपोर्ट',
    clinical_report_sub: 'डॉक्टर के लिए सारांश व सुरक्षा चेतावनी',
    health_history: 'मेरी मेडिकल हिस्ट्री',
    health_history_sub: 'पिछली बीमारियों और रिपोर्टों की समयरेखा',
    trusted_hospitals: 'विश्वसनीय अस्पताल',
    trusted_hospitals_sub: 'डेटा साझाकरण व अस्पताल अनुमतियां प्रबंधित करें',
    my_appointments: 'मेरी नियुक्तियाँ',
    my_appointments_sub: 'ओपीडी अपॉइंटमेंट बुक करें व टोकन देखें',
    emergency_active: 'आपातकालीन इंटेक सक्रिय',
    emergency_active_sub: 'गंभीर लक्षण पाए गए — अस्पताल एम्बुलेंस सक्रिय',
    ambulance_en_route: 'एम्बुलेंस रास्ते में है',
    eta_minutes: 'मिनट में आगमन',
    call_paramedic: 'पैरामेडिक को कॉल करें',
    live_telemetry: 'लाइव पैरामेडिक टेलीमेट्री एवं जीपीएस',
    paramedic_unit: 'पैरामेडिक यूनिट नियुक्त',
    view_live_map: 'लाइव एम्बुलेंस ट्रैकिंग देखें',
    original_statement: 'रोगी का मूल कथन',
    detected_concern: 'पहचानी गई आपातकालीन समस्या',
    siren_active: 'आपातकालीन सायरन चालू है',
    mute_siren: 'सायरन बंद करें',
    unmute_siren: 'सायरन चालू करें',
    dispatch_status_dispatched: 'एम्बुलेंस रवाना',
    dispatch_status_acknowledged: 'अस्पताल ने स्वीकार किया',
    dispatch_status_en_route: 'एम्बुलेंस रास्ते में है',
    dispatch_status_arrived: 'अस्पताल पहुँच गए',
    dispatch_status_resolved: 'आपातकाल समाप्त',
    speech_unsupported: 'इस ब्राउज़र में आवाज पहचान समर्थित नहीं है। कृपया लिखकर बताएं।',
    speech_error: 'आवाज पहचानने में समस्या हुई। कृपया लिखकर बताएं।',
    chat_placeholder: 'यहाँ अपने लक्षण लिखें या बोलें (जैसे तेज़ सीने में दर्द)...',
    send_btn: 'भेजें',
    start_here: 'यहाँ शुरू करें',
    ocr_badge: 'ओसीआर',
    report_badge: 'रिपोर्ट',
    history_badge: 'इतिहास',
    sharing_badge: 'शेयरिंग',
    booking_badge: 'बुकिंग'
  },
  mr: {
    app_title: 'मेडिब्रिज एआय (MediBridge AI)',
    app_tagline: 'घरापासून हॉस्पिटलपर्यंत एआय क्लिनिकल इंटेक प्लॅटफॉर्म',
    start_intake: 'एआय क्लिनिकल इंटेक सुरू करा',
    intake_subtitle: 'हॉस्पिटलमध्ये पोहोचण्यापूर्वी घरातूनच काही सोप्या प्रश्नांची उत्तरे द्या.',
    upload_records: 'वैद्यकीय कागदपत्रे व रिपोर्ट्स अपलोड करा',
    medical_timeline: 'वैद्यकीय इतिहास टाइमलाइन',
    doctor_dashboard: 'डॉक्टर प्री-अरायव्हल रांग',
    triage_command: 'हॉस्पिटल आपत्कालीन ट्रायज कमांड',
    admin_portal: 'सिस्टम अ‍ॅडमिन व अ‍ॅनालिटिक्स',
    emergency_callout: '🚨 तातडीची धोक्याची सूचना आढळली',
    requires_verification: 'एआय-व्युत्पन्न सारांश — डॉक्टरांकडून पडताळणी आवश्यक. हे अंतिम निदान नाही.',
    patient_id: 'रुग्ण आयडी (Patient ID)',
    abha_id: 'आभा आयडी (ABHA ID)',
    triage_priority: 'ट्रायज प्राधान्यक्रम',
    emergency_dispatch: 'आपत्कालीन अ‍ॅम्ब्युलन्स समन्वय',
    consent_title: 'रुग्ण संमती व गोपनीयता नियंत्रण',
    verify_record: 'वैद्यकीय तपासणी व पडताळणी',
    approve: 'पडताळणी करा व मंजूर करा',
    edit_summary: 'क्लिनिकल सारांश संपादित करा',
    reject_summary: 'नाकारा',
    select_hospital: 'हॉस्पिटल व विभाग निवडा',
    voice_input_start: 'बोलून सांगा',
    voice_input_stop: 'ऐकत आहे... थांबवण्यासाठी क्लिक करा',
    play_speech: 'एआय आवाज ऐका',
    talk_to_ai: 'एआयशी बोला',
    talk_to_ai_sub: 'घरातूनच बोलून किंवा लिहून लक्षणे सांगा',
    upload_report: 'रिपोर्ट अपलोड करा',
    upload_report_sub: 'ओसीआर द्वारे प्रिस्क्रिप्शन व लॅब रिपोर्ट्स स्कॅन करा',
    clinical_report: 'क्लिनिकल रिपोर्ट',
    clinical_report_sub: 'डॉक्टरांसाठी सारांश व सुरक्षिततेच्या सूचना',
    health_history: 'माझा वैद्यकीय इतिहास',
    health_history_sub: 'मागील आजार व तपासण्यांची टाइमलाइन',
    trusted_hospitals: 'विश्वासू हॉस्पिटल्स',
    trusted_hospitals_sub: 'डेटा शेअरिंग व परवानगी व्यवस्थापन',
    my_appointments: 'माझ्या अपॉइंटमेंट्स',
    my_appointments_sub: 'ओपीडी भेट बुक करा व टोकन पहा',
    emergency_active: 'आपत्कालीन इंटेक सक्रिय',
    emergency_active_sub: 'गंभीर लक्षणे आढळली — हॉस्पिटल अलर्ट सक्रिय',
    ambulance_en_route: 'अ‍ॅम्ब्युलन्स मार्गावर आहे',
    eta_minutes: 'मिनिटात आगमन',
    call_paramedic: 'पॅरामेडिकला कॉल करा',
    live_telemetry: 'थेट पॅरामेडिक टेलिमेट्री व जीपीएस',
    paramedic_unit: 'पॅरामेडिक युनिट तैनात',
    view_live_map: 'थेट अ‍ॅम्ब्युलन्स ट्रॅकिंग पहा',
    original_statement: 'रुग्णाचे मूळ विधान',
    detected_concern: 'आढळलेली तातडीची समस्या',
    siren_active: 'इमर्जन्सी सायरन सुरू आहे',
    mute_siren: 'सायरन बंद करा',
    unmute_siren: 'सायरन सुरू करा',
    dispatch_status_dispatched: 'अ‍ॅम्ब्युलन्स रवाना',
    dispatch_status_acknowledged: 'हॉस्पिटलने नोंद घेतली',
    dispatch_status_en_route: 'अ‍ॅम्ब्युलन्स मार्गावर आहे',
    dispatch_status_arrived: 'हॉस्पिटलमध्ये पोहोचले',
    dispatch_status_resolved: 'आपत्कालीन स्थिती समाप्त',
    speech_unsupported: 'या ब्राउझरमध्ये आवाज ओळख समर्थित नाही. कृपया लिहून सांगा.',
    speech_error: 'आवाज ओळखण्यात त्रुटी आली. कृपया लिहून सांगा.',
    chat_placeholder: 'येथे तुमची लक्षणे लिहा किंवा बोला (उदा. छातीत तीव्र वेदना)...',
    send_btn: 'पाठवा',
    start_here: 'येथून सुरू करा',
    ocr_badge: 'ओसीआर',
    report_badge: 'रिपोर्ट',
    history_badge: 'इतिहास',
    sharing_badge: 'शेअरिंग',
    booking_badge: 'बुकिंग'
  },
  ur: {
    app_title: 'میڈی برج اے آئی (MediBridge AI)',
    app_tagline: 'گھر سے ہسپتال تک کلینیکل انٹیک اور ایمرجنسی ٹرائیج پلیٹ فارم',
    start_intake: 'اے آئی کلینیکل انٹیک شروع کریں',
    intake_subtitle: 'ہسپتال پہنچنے سے پہلے گھر بیٹھے چند سوالات کے جواب دیں۔',
    upload_records: 'طبی دستاویزات اور رپورٹس اپ لوڈ کریں',
    medical_timeline: 'طبی تاریخ کا ٹائم لائن',
    doctor_dashboard: 'ڈاکٹر پری ارائیول قطار',
    triage_command: 'ہسپتال ایمرجنسی ٹرائیج کمانڈ',
    admin_portal: 'سسٹم ایڈمن اور اینالیٹکس',
    emergency_callout: '🚨 ہنگامی خطرے کا نشان ملا',
    requires_verification: 'اے آئی جنریٹڈ خلاصہ — ڈاکٹر کی تصدیق لازمی ہے۔',
    patient_id: 'مریض کی شناخت',
    abha_id: 'آبھا آئی ڈی',
    triage_priority: 'ٹرائیج ترجیح',
    emergency_dispatch: 'ایمرجنسی ایمبولینس کوآرڈینیشن',
    consent_title: 'مریض کی رضامندی اور پرائیویسی کنٹرول',
    verify_record: 'طبی معائنہ اور تصدیق',
    approve: 'تصدیق اور منظور کریں',
    edit_summary: 'کلینیکل خلاصہ میں ترمیم کریں',
    reject_summary: 'مسترد کریں',
    select_hospital: 'ہسپتال اور شعبہ منتخب کریں',
    voice_input_start: 'بول کر بتائیں',
    voice_input_stop: 'سن رہا ہے... مکمل کرنے کے لیے کلک کریں',
    play_speech: 'اے آئی آواز سنیں',
    talk_to_ai: 'اے آئی سے بات کریں',
    talk_to_ai_sub: 'گھر سے بول کر یا لکھ کر علامات بتائیں',
    upload_report: 'رپورٹ اپ لوڈ کریں',
    upload_report_sub: 'نسخے اور ٹیسٹ رپورٹس اسکین کریں',
    clinical_report: 'کلینیکل رپورٹ',
    clinical_report_sub: 'ڈاکٹر کے لیے خلاصہ اور حفاظتی انتباہات',
    health_history: 'میری میڈیکل تاریخ',
    health_history_sub: 'پچھلے امراض اور ٹیسٹ رپورٹس کی تاریخ',
    trusted_hospitals: 'قابل اعتماد ہسپتال',
    trusted_hospitals_sub: 'ڈیٹا شیئرنگ اور ہسپتال اجازتوں کا انتظام',
    my_appointments: 'میری اپائنٹمنٹس',
    my_appointments_sub: 'او پی ڈی اپائنٹمنٹ بک کریں اور ٹوکن دیکھیں',
    emergency_active: 'ہنگامی انٹیک فعال',
    emergency_active_sub: 'شدید علامات پائی گئیں — ہسپتال ایمبولینس روانہ',
    ambulance_en_route: 'ایمبولینس راستے میں ہے',
    eta_minutes: 'منٹ میں آمد',
    call_paramedic: 'پیرامیڈک کو کال کریں',
    live_telemetry: 'لائیو پیرامیڈک ٹیلی میٹری اور جی پی ایس',
    paramedic_unit: 'پیرامیڈک یونٹ تعینات',
    view_live_map: 'لائیو ایمبولینس ٹریکنگ دیکھیں',
    original_statement: 'مریض کا اصل بیان',
    detected_concern: 'شناخت شدہ ہنگامی مسئلہ',
    siren_active: 'ایمرجنسی سائرن جاری ہے',
    mute_siren: 'سائرن بند کریں',
    unmute_siren: 'سائرن آن کریں',
    dispatch_status_dispatched: 'ایمبولینس روانہ ہو گئی',
    dispatch_status_acknowledged: 'ہسپتال نے تسلیم کر لیا',
    dispatch_status_en_route: 'ایمبولینس راستے میں ہے',
    dispatch_status_arrived: 'ہسپتال پہنچ گئی',
    dispatch_status_resolved: 'ایمرجنسی حل ہو گئی',
    speech_unsupported: 'اس براؤزر میں آواز کی شناخت دستیاب نہیں ہے۔ براہ کرم لکھ کر بتائیں۔',
    speech_error: 'آواز پہچاننے میں مسئلہ ہوا۔ براہ کرم ٹائپ کریں۔',
    chat_placeholder: 'یہاں اپنی علامات لکھیں یا بولیں (مثلاً سینے میں شدید درد)...',
    send_btn: 'ارسال کریں',
    start_here: 'یہاں سے شروع کریں',
    ocr_badge: 'او سی آر',
    report_badge: 'رپورٹ',
    history_badge: 'تاریخ',
    sharing_badge: 'شیئرنگ',
    booking_badge: 'بکنگ'
  },
  kn: {
    app_title: 'ಮೆಡಿಬ್ರಿಡ್ಜ್ ಎಐ (MediBridge AI)',
    app_tagline: 'ಮನೆಯಿಂದ ಆಸ್ಪತ್ರೆಗೆ ಎಐ ಕ್ಲಿನಿಕಲ್ ಇನ್‌ಟೇಕ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
    start_intake: 'ಎಐ ಕ್ಲಿನಿಕಲ್ ಇನ್‌ಟೇಕ್ ಪ್ರಾರಂಭಿಸಿ',
    intake_subtitle: 'ಆಸ್ಪತ್ರೆಗೆ ತಲುಪುವ ಮುನ್ನ ಮನೆಯಲ್ಲೇ ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
    upload_records: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    medical_timeline: 'ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ ಟೈಮ್‌ಲೈನ್',
    doctor_dashboard: 'ವೈದ್ಯರ ಪ್ರಿ-ಅರೈವಲ್ ಸರದಿ',
    triage_command: 'ಆಸ್ಪತ್ರೆ ತುರ್ತು ಟ್ರಯಾಜ್ ಕಮಾಂಡ್',
    admin_portal: 'ಸಿಸ್ಟಮ್ ಅಡ್ಮಿನ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    emergency_callout: '🚨 ತುರ್ತು ಅಪಾಯದ ಎಚ್ಚರಿಕೆ ಪತ್ತೆಯಾಗಿದೆ',
    requires_verification: 'ಎಐ ಸಾರಾಂಶ — ವೈದ್ಯರ ಪರಿಶೀಲನೆ ಕಡ್ಡಾಯ. ಇದು ಅಂತಿಮ ರೋಗನಿರ್ಣಯವಲ್ಲ.',
    patient_id: 'ರೋಗಿಯ ಐಡಿ (Patient ID)',
    abha_id: 'ಆಭಾ ಐಡಿ (ABHA ID)',
    triage_priority: 'ಟ್ರಯಾಜ್ ಆದ್ಯತೆ',
    emergency_dispatch: 'ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ ಸಮನ್ವಯ',
    consent_title: 'ರೋಗಿಯ ಸಮ್ಮತಿ ಮತ್ತು ಗೌಪ್ಯತೆ ನಿಯಂತ್ರಣಗಳು',
    verify_record: 'ವೈದ್ಯರ ಪರಿಶೀಲನೆ ಮತ್ತು ದೃಢೀಕರಣ',
    approve: 'ಪರಿಶೀಲಿಸಿ ಅನುಮೋದಿಸಿ',
    edit_summary: 'ಕ್ಲಿನಿಕಲ್ ಸಾರಾಂಶ ಸಂಪಾದಿಸಿ',
    reject_summary: 'ತಿರಸ್ಕರಿಸಿ',
    select_hospital: 'ಆಸ್ಪತ್ರೆ ಮತ್ತು ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    voice_input_start: 'ಮಾತನಾಡಿ ತಿಳಿಸಿ',
    voice_input_stop: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    play_speech: 'ಎಐ ಧ್ವನಿ ಆಲಿಸಿ',
    talk_to_ai: 'ಎಐ ಜೊತೆ ಮಾತನಾಡಿ',
    talk_to_ai_sub: 'ಮನೆಯಲ್ಲೇ ಮಾತನಾಡಿ ಅಥವಾ ಬರೆದು ಲಕ್ಷಣಗಳನ್ನು ತಿಳಿಸಿ',
    upload_report: 'ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    upload_report_sub: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಮತ್ತು ಲ್ಯಾಬ್ ವರದಿಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    clinical_report: 'ಕ್ಲಿನಿಕಲ್ ವರದಿ',
    clinical_report_sub: 'ವೈದ್ಯರಿಗೆ ಸಾರಾಂಶ ಮತ್ತು ಸುರಕ್ಷತಾ ಎಚ್ಚರಿಕೆಗಳು',
    health_history: 'ನನ್ನ ಆರೋಗ್ಯ ಇತಿಹಾಸ',
    health_history_sub: 'ಹಿಂದಿನ ದಾಖಲೆಗಳ ಕಾಲಾನುಕ್ರಮದ ಟೈಮ್‌ಲೈನ್',
    trusted_hospitals: 'ವಿಶ್ವಾಸಾರ್ಹ ಆಸ್ಪತ್ರೆಗಳು',
    trusted_hospitals_sub: 'ಡೇಟಾ ಹಂಚಿಕೆ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಅನುಮತಿ ನಿರ್ವಹಿಸಿ',
    my_appointments: 'ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    my_appointments_sub: 'ಒಪಿಡಿ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಟೋಕನ್ ನೋಡಿ',
    emergency_active: 'ತುರ್ತು ಇನ್‌ಟೇಕ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    emergency_active_sub: 'ತೀವ್ರ ಲಕ್ಷಣಗಳು ಪತ್ತೆಯಾಗಿವೆ — ಆಸ್ಪತ್ರೆ ಆಂಬ್ಯುಲೆನ್ಸ್ ನಿಯೋಜಿಸಲಾಗಿದೆ',
    ambulance_en_route: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ದಾರಿಯಲ್ಲಿದೆ',
    eta_minutes: 'ನಿಮಿಷಗಳಲ್ಲಿ ಆಗಮನ',
    call_paramedic: 'ಪ್ಯಾರಾಮೆಡಿಕ್‌ಗೆ ಕರೆ ಮಾಡಿ',
    live_telemetry: 'ಲೈವ್ ಪ್ಯಾರಾಮೆಡಿಕ್ ಟೆಲಿಮೆಟ್ರಿ ಮತ್ತು ಜಿಪಿಎಸ್',
    paramedic_unit: 'ಪ್ಯಾರಾಮೆಡಿಕ್ ತಂಡ ನಿಯೋಜನೆ',
    view_live_map: 'ಲೈವ್ ಆಂಬ್ಯುಲೆನ್ಸ್ ಟ್ರ್ಯಾಕಿಂಗ್ ನೋಡಿ',
    original_statement: 'ರೋಗಿಯ ಮೂಲ ಹೇಳಿಕೆ',
    detected_concern: 'ಪತ್ತೆಯಾದ ತುರ್ತು ಸಮಸ್ಯೆ',
    siren_active: 'ತುರ್ತು ಸೈರನ್ ಚಾಲನೆಯಲ್ಲಿದೆ',
    mute_siren: 'ಸೈರನ್ ಮ್ಯೂಟ್ ಮಾಡಿ',
    unmute_siren: 'ಸೈರನ್ ಆನ್ ಮಾಡಿ',
    dispatch_status_dispatched: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ಹೊರಟಿದೆ',
    dispatch_status_acknowledged: 'ಆಸ್ಪತ್ರೆ ಸ್ವೀಕರಿಸಿದೆ',
    dispatch_status_en_route: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ದಾರಿಯಲ್ಲಿದೆ',
    dispatch_status_arrived: 'ಆಸ್ಪತ್ರೆ ತಲುಪಿದೆ',
    dispatch_status_resolved: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಮುಕ್ತಾಯ',
    speech_unsupported: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.',
    speech_error: 'ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆಯಲ್ಲಿ ದೋಷ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.',
    chat_placeholder: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ ಅಥವಾ ಮಾತನಾಡಿ (ಉದಾ: ಎದೆಯಲ್ಲಿ ತೀವ್ರ ನೋವು)...',
    send_btn: 'ಕಳುಹಿಸಿ',
    start_here: 'ಇಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ',
    ocr_badge: 'ಓಸಿಆರ್',
    report_badge: 'ವರದಿ',
    history_badge: 'ಇತಿಹಾಸ',
    sharing_badge: 'ಹಂಚಿಕೆ',
    booking_badge: 'ಬುಕಿಂಗ್'
  },
  gu: {
    app_title: 'મેડિબ્રિજ એઆઈ (MediBridge AI)',
    app_tagline: 'ઘરથી હોસ્પિટલ એઆઈ ક્લિનિકલ ઇનટેક પ્લેટફોર્મ',
    start_intake: 'એઆઈ ક્લિનિકલ ઇનટેક શરૂ કરો',
    intake_subtitle: 'હોસ્પિટલ પહોંચતા પહેલા ઘરેથી જ સરળ પ્રશ્નોના જવાબ આપો.',
    upload_records: 'મેડિકલ દસ્તાવેજો અપલોડ કરો',
    medical_timeline: 'મેડિકલ હિસ્ટ્રી ટાઇમલાઇન',
    doctor_dashboard: 'ડોક્ટર પ્રી-અરાઇવલ કતાર',
    triage_command: 'હોસ્પિટલ ઇમરજન્સી ટ્રાયજ કમાન્ડ',
    admin_portal: 'સિસ્ટમ એડમિન અને એનાલિટિક્સ',
    emergency_callout: '🚨 કટોકટીનો લાલ સંકેત મળ્યો',
    requires_verification: 'એઆઈ સારાંશ — ડોક્ટર દ્વારા ચકાસણી ફરજિયાત છે.',
    patient_id: 'દર્દી આઈડી (Patient ID)',
    abha_id: 'આભા આઈડી (ABHA ID)',
    triage_priority: 'ટ્રાયજ પ્રાથમિકતા',
    emergency_dispatch: 'ઇમરજન્સી એમ્બ્યુલન્સ સંકલન',
    consent_title: 'દર્દી સંમતિ અને ગોપનીયતા નિયંત્રણો',
    verify_record: 'ડોક્ટર સમીક્ષા અને ચકાસણી',
    approve: 'ચકાસો અને મંજૂર કરો',
    edit_summary: 'ક્લિનિકલ સારાંશ સંપાદિત કરો',
    reject_summary: 'અસ્વીકાર કરો',
    select_hospital: 'હોસ્પિટલ અને વિભાગ પસંદ કરો',
    voice_input_start: 'બોલીને જણાવો',
    voice_input_stop: 'સાંભળી રહ્યું છે... બંધ કરવા ક્લિક કરો',
    play_speech: 'એઆઈ અવાજ સાંભળો',
    talk_to_ai: 'એઆઈ સાથે વાત કરો',
    talk_to_ai_sub: 'ઘરેથી બોલીને અથવા લખીને લક્ષણો જણાવો',
    upload_report: 'રિપોર્ટ અપલોડ કરો',
    upload_report_sub: 'પ્રિસ્ક્રિપ્શન અને લેબ રિપોર્ટ સ્કેન કરો',
    clinical_report: 'ક્લિનિકલ રિપોર્ટ',
    clinical_report_sub: 'ડોક્ટર માટે સારાંશ અને સુરક્ષા ચેતવણીઓ',
    health_history: 'મારો આરોગ્ય ઇતિહાસ',
    health_history_sub: 'પાછલા રેકોર્ડ્સની સમયરેખા',
    trusted_hospitals: 'વિશ્વસનીય હોસ્પિટલો',
    trusted_hospitals_sub: 'ડેટા શેરિંગ અને પરવાનગી સંચાલન',
    my_appointments: 'મારી એપોઇન્ટમેન્ટ્સ',
    my_appointments_sub: 'ઓપીડી બુક કરો અને ટોકન જુઓ',
    emergency_active: 'કટોકટી ઇનટેક સક્રિય',
    emergency_active_sub: 'ગંભીર લક્ષણો મળ્યા — એમ્બ્યુલન્સ રવાના',
    ambulance_en_route: 'એમ્બ્યુલન્સ રસ્તામાં છે',
    eta_minutes: 'મિનિટમાં આગમન',
    call_paramedic: 'પેરામેડિકને કોલ કરો',
    live_telemetry: 'લાઇવ પેરામેડિક ટેલિમેટ્રી અને જીપીએસ',
    paramedic_unit: 'પેરામેડિક ટીમ નિયુક્ત',
    view_live_map: 'લાઇવ એમ્બ્યુલન્સ ટ્રેકિંગ જુઓ',
    original_statement: 'દર્દીનું મૂળ નિવેદન',
    detected_concern: 'ઓળખાયેલી કટોકટી સમસ્યા',
    siren_active: 'ઇમરજન્સી સાયરન ચાલુ છે',
    mute_siren: 'સાયરન બંધ કરો',
    unmute_siren: 'સાયરન ચાલુ કરો',
    dispatch_status_dispatched: 'એમ્બ્યુલન્સ રવાના થઈ',
    dispatch_status_acknowledged: 'હોસ્પિટલે સ્વીકાર્યું',
    dispatch_status_en_route: 'એમ્બ્યુલન્સ રસ્તામાં છે',
    dispatch_status_arrived: 'હોસ્પિટલ પહોંચી ગયા',
    dispatch_status_resolved: 'કટોકટી ઉકેલાઈ ગઈ',
    speech_unsupported: 'આ બ્રાઉઝરમાં અવાજ ઓળખ ઉપલબ્ધ નથી. કૃપા કરીને લખીને જણાવો.',
    speech_error: 'અવાજ ઓળખવામાં ભૂલ આવી. કૃપા કરીને ટાઇપ કરો.',
    chat_placeholder: 'અહીં તમારા લક્ષણો લખો અથવા બોલો (દા.ત. છાતીમાં તીવ્ર દુખાવો)...',
    send_btn: 'મોકલો',
    start_here: 'અહીંથી શરૂ કરો',
    ocr_badge: 'ઓસીઆર',
    report_badge: 'રિપોર્ટ',
    history_badge: 'ઇતિહાસ',
    sharing_badge: 'શેરિંગ',
    booking_badge: 'બુકિંગ'
  },
  ta: {
    app_title: 'மெடிபிரிட்ஜ் ஏஐ (MediBridge AI)',
    app_tagline: 'வீட்டிலிருந்து மருத்துவமனைக்கான ஏஐ கிளினிக்கல் இன்டேக் தளம்',
    start_intake: 'ஏஐ கிளினிக்கல் இன்டேக் தொடங்கவும்',
    intake_subtitle: 'மருத்துவமனைக்கு வருவதற்கு முன் வீட்டிலிருந்தே எளிய கேள்விகளுக்கு பதிலளிக்கவும்.',
    upload_records: 'மருத்துவ ஆவணங்களைப் பதிவேற்றவும்',
    medical_timeline: 'மருத்துவ வரலாறு காலவரிசை',
    doctor_dashboard: 'மருத்துவர் முன்-வருகை வரிசை',
    triage_command: 'மருத்துவமனை அவசர சிகிச்சை கட்டளை மையம்',
    admin_portal: 'கணினி நிர்வாகம் & பகுப்பாய்வு',
    emergency_callout: '🚨 அவசர சிவப்பு எச்சரிக்கை கண்டறியப்பட்டது',
    requires_verification: 'ஏஐ உருவாக்கிய சுருக்கம் — மருத்துவரின் சரிபார்ப்பு அவசியம்.',
    patient_id: 'நோயாளி ஐடி (Patient ID)',
    abha_id: 'ஆபா ஐடி (ABHA ID)',
    triage_priority: 'ட்ரையേജ് முன்னுரிமை',
    emergency_dispatch: 'அவசர ஆம்புலன்ஸ் ஒருங்கிணைப்பு',
    consent_title: 'நோயாளி ஒப்புதல் மற்றும் தனியுரிமை கட்டுப்பாடுகள்',
    verify_record: 'மருத்துவர் மதிப்பாய்வு & சரிபார்ப்பு',
    approve: 'சரிபார்த்து அங்கீகரிக்கவும்',
    edit_summary: 'சுருக்கத்தைத் திருத்தவும்',
    reject_summary: 'நிராகரிக்கவும்',
    select_hospital: 'மருத்துவமனை மற்றும் துறையைத் தேர்வுசெய்க',
    voice_input_start: 'பேசிப் பதிவு செய்க',
    voice_input_stop: 'கேட்கிறது... முடிக்க கிளிக் செய்யவும்',
    play_speech: 'ஏஐ குரலைக் கேளுங்கள்',
    talk_to_ai: 'ஏஐ-யிடம் பேசவும்',
    talk_to_ai_sub: 'வீட்டிலிருந்தே பேசியோ எழுதியோ அறிகுறிகளைக் கூறவும்',
    upload_report: 'அறிக்கையைப் பதிவேற்றவும்',
    upload_report_sub: 'மருந்துச் சீட்டு மற்றும் இரத்த பரிசோதனை ஸ்கேன் செய்க',
    clinical_report: 'கிளினிக்கல் அறிக்கை',
    clinical_report_sub: 'மருத்துவருக்கான சுருக்கம் மற்றும் எச்சரிக்கைகள்',
    health_history: 'எனது மருத்துவ வரலாறு',
    health_history_sub: 'முந்தைய பதிவுகளின் காலவரிசை',
    trusted_hospitals: 'நம்பகமான மருத்துவமனைகள்',
    trusted_hospitals_sub: 'தரவு பகிர்வு மற்றும் அனுமதிகளை நிர்வகிக்கவும்',
    my_appointments: 'எனது முன்பதிவுகள்',
    my_appointments_sub: 'ஓபிடி முன்பதிவு செய்து டோக்கனைப் பார்க்கவும்',
    emergency_active: 'அவசர இன்டேக் செயலில் உள்ளது',
    emergency_active_sub: 'தீவிர அறிகுறிகள் கண்டறியப்பட்டன — ஆம்புலன்ஸ் அனுப்பப்பட்டது',
    ambulance_en_route: 'ஆம்புலன்ஸ் வழியில் உள்ளது',
    eta_minutes: 'நிமிடங்களில் வருகை',
    call_paramedic: 'மருத்துவ உதவியாளரை அழைக்கவும்',
    live_telemetry: 'நேரலை டெலிமெட்ரி மற்றும் ஜிபிஎஸ்',
    paramedic_unit: 'அவசர மருத்துவக் குழு நியமிக்கப்பட்டது',
    view_live_map: 'நேரலை ஆம்புலன்ஸ் கண்காணிப்பைப் பார்க்கவும்',
    original_statement: 'நோயாளியின் அசல் கூற்று',
    detected_concern: 'கண்டறியப்பட்ட அவசரக் கவலை',
    siren_active: 'அவசர சைரன் ஒலிக்கிறது',
    mute_siren: 'சைரனை நிறுத்து',
    unmute_siren: 'சைரனை இயக்கு',
    dispatch_status_dispatched: 'ஆம்புலன்ஸ் புறப்பட்டது',
    dispatch_status_acknowledged: 'மருத்துவமனை ஏற்றுக்கொண்டது',
    dispatch_status_en_route: 'ஆம்புலன்ஸ் வழியில் உள்ளது',
    dispatch_status_arrived: 'மருத்துவமனையை அடைந்தது',
    dispatch_status_resolved: 'அவசரம் தீர்க்கப்பட்டது',
    speech_unsupported: 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை. தட்டச்சு செய்யவும்.',
    speech_error: 'குரல் அறிதலில் பிழை. தயவுசெய்து தட்டச்சு செய்யவும்.',
    chat_placeholder: 'உங்கள் அறிகுறிகளை இங்கே எழுதவும் அல்லது பேசவும் (எ.கா. நெஞ்சில் கடுமையான வலி)...',
    send_btn: 'அனுப்புக',
    start_here: 'இங்கே தொடங்கவும்',
    ocr_badge: 'ஓசிஆர்',
    report_badge: 'அறிக்கை',
    history_badge: 'வரலாறு',
    sharing_badge: 'பகிர்வு',
    booking_badge: 'முன்பதிவு'
  },
  bn: {
    app_title: 'মেডিব্রিজ এআই (MediBridge AI)',
    app_tagline: 'বাড়ি থেকে হাসপাতাল এআই ক্লিনিকাল ইনটেক প্ল্যাটফর্ম',
    start_intake: 'এআই ক্লিনিকাল ইনটেক শুরু করুন',
    intake_subtitle: 'হাসপাতালে পৌঁছানোর আগে বাড়ি বসেই কয়েকটি সহজ প্রশ্নের উত্তর দিন।',
    upload_records: 'মেডিকেল ডকুমেন্ট ও রিপোর্ট আপলোড করুন',
    medical_timeline: 'মেডিকেল হিস্ট্রি টাইমলাইন',
    doctor_dashboard: 'ডাক্তার প্রি-অ্যারাইভাল সারি',
    triage_command: 'হাসপাতাল জরুরি ট্রায়াজ কমান্ড',
    admin_portal: 'সিস্টেম অ্যাডমিন ও অ্যানালিটিক্স',
    emergency_callout: '🚨 জরুরি রেড ফ্ল্যাগ সতর্কতা সনাক্ত হয়েছে',
    requires_verification: 'এআই-তৈরি সারাংশ — ডাক্তারের যাচাইকরণ বাধ্যতামূলক। এটি চূড়ান্ত রোগ নির্ণয় নয়।',
    patient_id: 'রোগী আইডি (Patient ID)',
    abha_id: 'আভা আইডি (ABHA ID)',
    triage_priority: 'ট্রায়াজ অগ্রাধিকার',
    emergency_dispatch: 'জরুরি অ্যাম্বুলেন্স সমন্বয়',
    consent_title: 'রোগীর সম্মতি ও গোপনীয়তা নিয়ন্ত্রণ',
    verify_record: 'চিকিৎসক পর্যালোচনা ও যাচাইকরণ',
    approve: 'যাচাই ও অনুমোদন করুন',
    edit_summary: 'ক্লিনিকাল সারাংশ সম্পাদনা করুন',
    reject_summary: 'প্রত্যাখ্যান করুন',
    select_hospital: 'হাসপাতাল ও বিভাগ নির্বাচন করুন',
    voice_input_start: 'মুখে বলে জানান',
    voice_input_stop: 'শুনছে... শেষ করতে ক্লিক করুন',
    play_speech: 'এআই ভয়েস শুনুন',
    talk_to_ai: 'এআই-এর সাথে কথা বলুন',
    talk_to_ai_sub: 'বাড়ি থেকে কথা বলে বা লিখে লক্ষণ জানান',
    upload_report: 'রিপোর্ট আপলোড করুন',
    upload_report_sub: 'প্রেসক্রিপশন ও ল্যাব টেস্ট স্ক্যান করুন',
    clinical_report: 'ক্লিনিকাল রিপোর্ট',
    clinical_report_sub: 'ডাক্তারের জন্য সারাংশ ও নিরাপত্তা সতর্কতা',
    health_history: 'আমার স্বাস্থ্য ইতিহাস',
    health_history_sub: 'পূর্বের মেডিকেল রেকর্ডের সময়রেখা',
    trusted_hospitals: 'বিশ্বস্ত হাসপাতাল',
    trusted_hospitals_sub: 'ডেটা শেয়ারিং ও হাসপাতালের অনুমতি পরিচালনা করুন',
    my_appointments: 'আমার অ্যাপয়েন্টমেন্ট',
    my_appointments_sub: 'ওপিডি বুকিং করুন ও টোকেন দেখুন',
    emergency_active: 'জরুরি ইনটেক সক্রিয়',
    emergency_active_sub: 'মারাত্মক লক্ষণ সনাক্ত হয়েছে — অ্যাম্বুলেন্স পাঠানো হয়েছে',
    ambulance_en_route: 'অ্যাম্বুলেন্স পথে আছে',
    eta_minutes: 'মিনিটের মধ্যে পৌঁছাবে',
    call_paramedic: 'প্যারামেডিককে কল করুন',
    live_telemetry: 'লাইভ প্যারামেডিক টেলিমেট্রি ও জিপিএস',
    paramedic_unit: 'প্যারামেডিক টিম মোতায়েন',
    view_live_map: 'লাইভ অ্যাম্বুলেন্স ট্র্যাকিং দেখুন',
    original_statement: 'রোগীর আসল বক্তব্য',
    detected_concern: 'সনাক্তকৃত জরুরি সমস্যা',
    siren_active: 'জরুরি সাইরেন বাজছে',
    mute_siren: 'সাইরেন মিউট করুন',
    unmute_siren: 'সাইরেন চালু করুন',
    dispatch_status_dispatched: 'অ্যাম্বুলেন্স রওনা হয়েছে',
    dispatch_status_acknowledged: 'হাসপাতাল গ্রহণ করেছে',
    dispatch_status_en_route: 'অ্যাম্বুলেন্স পথে আছে',
    dispatch_status_arrived: 'হাসপাতালে পৌঁছেছে',
    dispatch_status_resolved: 'জরুরি অবস্থা সমাধান হয়েছে',
    speech_unsupported: 'এই ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়। অনুগ্রহ করে লিখে জানান।',
    speech_error: 'ভয়েস সনাক্তকরণে সমস্যা হয়েছে। অনুগ্রহ করে লিখে জানান।',
    chat_placeholder: 'এখানে আপনার লক্ষণগুলি লিখুন বা বলুন (যেমন বুকে তীব্র ব্যথা)...',
    send_btn: 'পাঠান',
    start_here: 'এখানে শুরু করুন',
    ocr_badge: 'ওসিআর',
    report_badge: 'রিপোর্ট',
    history_badge: 'ইতিহাস',
    sharing_badge: 'শেয়ারিং',
    booking_badge: 'বুকিং'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    if (saved && ['en', 'hi', 'mr', 'ur', 'kn', 'gu', 'ta', 'bn'].includes(saved)) {
      return saved;
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // ignore storage errors
    }
  };

  useEffect(() => {
    // Keep application UI structure strictly LTR globally.
    // RTL text formatting is applied at the component/text level for Urdu.
    document.documentElement.setAttribute('dir', 'ltr');
  }, [language]);

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const isRTL = language === 'ur';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
